[2024-02-11 14:25:00] INFO (nni.experiment) Creating experiment, Experiment ID: pi7wqhfz
[2024-02-11 14:25:00] INFO (nni.experiment) Starting web server...
[2024-02-11 14:25:01] WARNING (nni.experiment) Timeout, retry...
[2024-02-11 14:25:02] WARNING (nni.experiment) Timeout, retry...
[2024-02-11 14:25:03] ERROR (nni.experiment) Create experiment failed: HTTPConnectionPool(host='localhost', port=8020): Max retries exceeded with url: /api/v1/nni/check-status (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fae8c166580>: Failed to establish a new connection: [Errno 111] Connection refused'))
[2024-02-11 14:25:03] INFO (nni.experiment) Creating experiment, Experiment ID: pi7wqhfz
[2024-02-11 14:25:03] INFO (nni.experiment) Starting web server...
[2024-02-11 14:25:04] WARNING (nni.experiment) Timeout, retry...
[2024-02-11 14:25:05] WARNING (nni.experiment) Timeout, retry...
[2024-02-11 14:25:06] ERROR (nni.experiment) Create experiment failed: HTTPConnectionPool(host='localhost', port=8021): Max retries exceeded with url: /api/v1/nni/check-status (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fae8c166c70>: Failed to establish a new connection: [Errno 111] Connection refused'))
[2024-02-11 14:25:06] INFO (nni.experiment) Creating experiment, Experiment ID: pi7wqhfz
[2024-02-11 14:25:06] INFO (nni.experiment) Starting web server...
[2024-02-11 14:25:07] WARNING (nni.experiment) Timeout, retry...
[2024-02-11 14:25:08] WARNING (nni.experiment) Timeout, retry...
[2024-02-11 14:25:09] ERROR (nni.experiment) Create experiment failed: HTTPConnectionPool(host='localhost', port=8022): Max retries exceeded with url: /api/v1/nni/check-status (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fae8c164a90>: Failed to establish a new connection: [Errno 111] Connection refused'))
[2024-02-11 14:25:09] INFO (nni.experiment) Creating experiment, Experiment ID: pi7wqhfz
[2024-02-11 14:25:09] INFO (nni.experiment) Starting web server...
[2024-02-11 14:25:10] WARNING (nni.experiment) Timeout, retry...
[2024-02-11 14:25:11] WARNING (nni.experiment) Timeout, retry...
[2024-02-11 14:25:13] ERROR (nni.experiment) Create experiment failed: HTTPConnectionPool(host='localhost', port=8023): Max retries exceeded with url: /api/v1/nni/check-status (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fae8c1bd190>: Failed to establish a new connection: [Errno 111] Connection refused'))
[2024-02-11 14:25:13] INFO (nni.experiment) Creating experiment, Experiment ID: pi7wqhfz
[2024-02-11 14:25:13] INFO (nni.experiment) Starting web server...
[2024-02-11 14:25:14] WARNING (nni.experiment) Timeout, retry...
[2024-02-11 14:25:15] WARNING (nni.experiment) Timeout, retry...
[2024-02-11 14:25:16] ERROR (nni.experiment) Create experiment failed: HTTPConnectionPool(host='localhost', port=8024): Max retries exceeded with url: /api/v1/nni/check-status (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fae8c1bd3d0>: Failed to establish a new connection: [Errno 111] Connection refused'))
[2024-02-11 14:25:16] INFO (nni.experiment) Creating experiment, Experiment ID: pi7wqhfz
[2024-02-11 14:25:16] INFO (nni.experiment) Starting web server...
[2024-02-11 14:25:17] WARNING (nni.experiment) Timeout, retry...
[2024-02-11 14:25:18] WARNING (nni.experiment) Timeout, retry...
[2024-02-11 14:25:19] ERROR (nni.experiment) Create experiment failed: HTTPConnectionPool(host='localhost', port=8025): Max retries exceeded with url: /api/v1/nni/check-status (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fae8c1bd310>: Failed to establish a new connection: [Errno 111] Connection refused'))
[2024-02-11 14:25:19] INFO (nni.experiment) Creating experiment, Experiment ID: pi7wqhfz
[2024-02-11 14:25:19] INFO (nni.experiment) Starting web server...
[2024-02-11 14:25:20] WARNING (nni.experiment) Timeout, retry...
[2024-02-11 14:25:21] WARNING (nni.experiment) Timeout, retry...
[2024-02-11 14:25:22] ERROR (nni.experiment) Create experiment failed: HTTPConnectionPool(host='localhost', port=8026): Max retries exceeded with url: /api/v1/nni/check-status (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fae8c1bddc0>: Failed to establish a new connection: [Errno 111] Connection refused'))
[2024-02-11 14:25:22] INFO (nni.experiment) Creating experiment, Experiment ID: pi7wqhfz
[2024-02-11 14:25:22] INFO (nni.experiment) Starting web server...
[2024-02-11 14:25:23] WARNING (nni.experiment) Timeout, retry...
[2024-02-11 14:25:24] WARNING (nni.experiment) Timeout, retry...
[2024-02-11 14:25:25] ERROR (nni.experiment) Create experiment failed: HTTPConnectionPool(host='localhost', port=8027): Max retries exceeded with url: /api/v1/nni/check-status (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fae8c17fca0>: Failed to establish a new connection: [Errno 111] Connection refused'))
[2024-02-11 14:25:25] INFO (nni.experiment) Creating experiment, Experiment ID: pi7wqhfz
[2024-02-11 14:25:25] INFO (nni.experiment) Starting web server...
[2024-02-11 14:25:26] WARNING (nni.experiment) Timeout, retry...
[2024-02-11 14:25:27] WARNING (nni.experiment) Timeout, retry...
[2024-02-11 14:25:28] ERROR (nni.experiment) Create experiment failed: HTTPConnectionPool(host='localhost', port=8028): Max retries exceeded with url: /api/v1/nni/check-status (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fae8c17fd60>: Failed to establish a new connection: [Errno 111] Connection refused'))
[2024-02-11 14:25:28] INFO (nni.experiment) Creating experiment, Experiment ID: pi7wqhfz
[2024-02-11 14:25:28] INFO (nni.experiment) Starting web server...
[2024-02-11 14:25:29] WARNING (nni.experiment) Timeout, retry...
[2024-02-11 14:25:30] WARNING (nni.experiment) Timeout, retry...
[2024-02-11 14:25:31] ERROR (nni.experiment) Create experiment failed: HTTPConnectionPool(host='localhost', port=8029): Max retries exceeded with url: /api/v1/nni/check-status (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fae8c10b130>: Failed to establish a new connection: [Errno 111] Connection refused'))
[2024-02-11 14:25:31] INFO (nni.experiment) Creating experiment, Experiment ID: pi7wqhfz
[2024-02-11 14:25:31] INFO (nni.experiment) Starting web server...
[2024-02-11 14:25:32] WARNING (nni.experiment) Timeout, retry...
[2024-02-11 14:25:33] WARNING (nni.experiment) Timeout, retry...
[2024-02-11 14:25:34] ERROR (nni.experiment) Create experiment failed: HTTPConnectionPool(host='localhost', port=8030): Max retries exceeded with url: /api/v1/nni/check-status (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fae8c10ecd0>: Failed to establish a new connection: [Errno 111] Connection refused'))
[2024-02-11 14:25:34] INFO (nni.experiment) Creating experiment, Experiment ID: pi7wqhfz
[2024-02-11 14:25:34] INFO (nni.experiment) Starting web server...
[2024-02-11 14:25:35] WARNING (nni.experiment) Timeout, retry...
[2024-02-11 14:25:36] WARNING (nni.experiment) Timeout, retry...
[2024-02-11 14:25:37] ERROR (nni.experiment) Create experiment failed: HTTPConnectionPool(host='localhost', port=8031): Max retries exceeded with url: /api/v1/nni/check-status (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fae8c1168e0>: Failed to establish a new connection: [Errno 111] Connection refused'))
[2024-02-11 14:25:37] INFO (nni.experiment) Creating experiment, Experiment ID: pi7wqhfz
[2024-02-11 14:25:37] INFO (nni.experiment) Starting web server...
[2024-02-11 14:25:38] WARNING (nni.experiment) Timeout, retry...
[2024-02-11 14:25:39] WARNING (nni.experiment) Timeout, retry...
[2024-02-11 14:25:40] ERROR (nni.experiment) Create experiment failed: HTTPConnectionPool(host='localhost', port=8032): Max retries exceeded with url: /api/v1/nni/check-status (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fae8c11e130>: Failed to establish a new connection: [Errno 111] Connection refused'))
[2024-02-11 14:25:40] INFO (nni.experiment) Creating experiment, Experiment ID: pi7wqhfz
[2024-02-11 14:25:40] INFO (nni.experiment) Starting web server...
[2024-02-11 14:25:41] WARNING (nni.experiment) Timeout, retry...
[2024-02-11 14:25:42] WARNING (nni.experiment) Timeout, retry...
[2024-02-11 14:25:43] ERROR (nni.experiment) Create experiment failed: HTTPConnectionPool(host='localhost', port=8033): Max retries exceeded with url: /api/v1/nni/check-status (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fae8c11e130>: Failed to establish a new connection: [Errno 111] Connection refused'))
[2024-02-11 14:25:43] INFO (nni.experiment) Creating experiment, Experiment ID: pi7wqhfz
[2024-02-11 14:25:43] INFO (nni.experiment) Starting web server...
[2024-02-11 14:25:44] WARNING (nni.experiment) Timeout, retry...
[2024-02-11 14:25:45] WARNING (nni.experiment) Timeout, retry...
[2024-02-11 14:25:46] ERROR (nni.experiment) Create experiment failed: HTTPConnectionPool(host='localhost', port=8034): Max retries exceeded with url: /api/v1/nni/check-status (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fae8c1220d0>: Failed to establish a new connection: [Errno 111] Connection refused'))
[2024-02-11 14:25:46] INFO (nni.experiment) Creating experiment, Experiment ID: pi7wqhfz
[2024-02-11 14:25:46] INFO (nni.experiment) Starting web server...
[2024-02-11 14:25:47] WARNING (nni.experiment) Timeout, retry...
[2024-02-11 14:25:48] WARNING (nni.experiment) Timeout, retry...
[2024-02-11 14:25:49] ERROR (nni.experiment) Create experiment failed: HTTPConnectionPool(host='localhost', port=8035): Max retries exceeded with url: /api/v1/nni/check-status (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fae8c122ee0>: Failed to establish a new connection: [Errno 111] Connection refused'))
[2024-02-11 14:25:49] INFO (nni.experiment) Creating experiment, Experiment ID: pi7wqhfz
[2024-02-11 14:25:49] INFO (nni.experiment) Starting web server...
[2024-02-11 14:25:50] WARNING (nni.experiment) Timeout, retry...
[2024-02-11 14:25:51] WARNING (nni.experiment) Timeout, retry...
[2024-02-11 14:25:52] ERROR (nni.experiment) Create experiment failed: HTTPConnectionPool(host='localhost', port=8036): Max retries exceeded with url: /api/v1/nni/check-status (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fae8c126af0>: Failed to establish a new connection: [Errno 111] Connection refused'))
[2024-02-11 14:25:52] INFO (nni.experiment) Creating experiment, Experiment ID: pi7wqhfz
[2024-02-11 14:25:52] INFO (nni.experiment) Starting web server...
[2024-02-11 14:25:53] WARNING (nni.experiment) Timeout, retry...
[2024-02-11 14:25:54] WARNING (nni.experiment) Timeout, retry...
[2024-02-11 14:25:55] ERROR (nni.experiment) Create experiment failed: HTTPConnectionPool(host='localhost', port=8037): Max retries exceeded with url: /api/v1/nni/check-status (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fae8c129580>: Failed to establish a new connection: [Errno 111] Connection refused'))
[2024-02-11 14:25:55] INFO (nni.experiment) Creating experiment, Experiment ID: pi7wqhfz
[2024-02-11 14:25:55] INFO (nni.experiment) Starting web server...
[2024-02-11 14:25:56] WARNING (nni.experiment) Timeout, retry...
[2024-02-11 14:25:57] WARNING (nni.experiment) Timeout, retry...
[2024-02-11 14:25:58] ERROR (nni.experiment) Create experiment failed: HTTPConnectionPool(host='localhost', port=8038): Max retries exceeded with url: /api/v1/nni/check-status (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fae8c12f100>: Failed to establish a new connection: [Errno 111] Connection refused'))
[2024-02-11 14:25:58] INFO (nni.experiment) Creating experiment, Experiment ID: pi7wqhfz
[2024-02-11 14:25:58] INFO (nni.experiment) Starting web server...
[2024-02-11 14:25:59] WARNING (nni.experiment) Timeout, retry...
[2024-02-11 14:26:00] WARNING (nni.experiment) Timeout, retry...
[2024-02-11 14:26:01] ERROR (nni.experiment) Create experiment failed: HTTPConnectionPool(host='localhost', port=8039): Max retries exceeded with url: /api/v1/nni/check-status (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fae8c10b4c0>: Failed to establish a new connection: [Errno 111] Connection refused'))
[2024-02-11 14:26:01] INFO (nni.experiment) Creating experiment, Experiment ID: pi7wqhfz
[2024-02-11 14:26:01] INFO (nni.experiment) Starting web server...
[2024-02-11 14:26:02] WARNING (nni.experiment) Timeout, retry...
[2024-02-11 14:26:03] WARNING (nni.experiment) Timeout, retry...
[2024-02-11 14:26:04] ERROR (nni.experiment) Create experiment failed: HTTPConnectionPool(host='localhost', port=8040): Max retries exceeded with url: /api/v1/nni/check-status (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fae8c1330d0>: Failed to establish a new connection: [Errno 111] Connection refused'))
[2024-02-11 14:26:04] INFO (nni.experiment) Creating experiment, Experiment ID: pi7wqhfz
[2024-02-11 14:26:04] INFO (nni.experiment) Starting web server...
[2024-02-11 14:26:06] WARNING (nni.experiment) Timeout, retry...
[2024-02-11 14:26:07] WARNING (nni.experiment) Timeout, retry...
[2024-02-11 14:26:08] ERROR (nni.experiment) Create experiment failed: HTTPConnectionPool(host='localhost', port=8041): Max retries exceeded with url: /api/v1/nni/check-status (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fae8c133640>: Failed to establish a new connection: [Errno 111] Connection refused'))
[2024-02-11 14:26:08] INFO (nni.experiment) Creating experiment, Experiment ID: pi7wqhfz
[2024-02-11 14:26:08] INFO (nni.experiment) Starting web server...
[2024-02-11 14:26:09] WARNING (nni.experiment) Timeout, retry...
[2024-02-11 14:26:10] WARNING (nni.experiment) Timeout, retry...
[2024-02-11 14:26:11] ERROR (nni.experiment) Create experiment failed: HTTPConnectionPool(host='localhost', port=8042): Max retries exceeded with url: /api/v1/nni/check-status (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fae8c135700>: Failed to establish a new connection: [Errno 111] Connection refused'))
[2024-02-11 14:26:11] INFO (nni.experiment) Creating experiment, Experiment ID: pi7wqhfz
[2024-02-11 14:26:11] INFO (nni.experiment) Starting web server...
[2024-02-11 14:26:12] WARNING (nni.experiment) Timeout, retry...
[2024-02-11 14:26:13] WARNING (nni.experiment) Timeout, retry...
[2024-02-11 14:26:14] ERROR (nni.experiment) Create experiment failed: HTTPConnectionPool(host='localhost', port=8043): Max retries exceeded with url: /api/v1/nni/check-status (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fae8c135700>: Failed to establish a new connection: [Errno 111] Connection refused'))
[2024-02-11 14:26:14] INFO (nni.experiment) Creating experiment, Experiment ID: pi7wqhfz
[2024-02-11 14:26:14] INFO (nni.experiment) Starting web server...
[2024-02-11 14:26:15] WARNING (nni.experiment) Timeout, retry...
[2024-02-11 14:26:16] WARNING (nni.experiment) Timeout, retry...
[2024-02-11 14:26:17] ERROR (nni.experiment) Create experiment failed: HTTPConnectionPool(host='localhost', port=8044): Max retries exceeded with url: /api/v1/nni/check-status (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fae8c138550>: Failed to establish a new connection: [Errno 111] Connection refused'))
[2024-02-11 14:26:17] INFO (nni.experiment) Creating experiment, Experiment ID: pi7wqhfz
[2024-02-11 14:26:17] INFO (nni.experiment) Starting web server...
[2024-02-11 14:26:18] WARNING (nni.experiment) Timeout, retry...
[2024-02-11 14:26:19] WARNING (nni.experiment) Timeout, retry...
[2024-02-11 14:26:20] ERROR (nni.experiment) Create experiment failed: HTTPConnectionPool(host='localhost', port=8045): Max retries exceeded with url: /api/v1/nni/check-status (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fae8c126dc0>: Failed to establish a new connection: [Errno 111] Connection refused'))
[2024-02-11 14:26:20] INFO (nni.experiment) Creating experiment, Experiment ID: pi7wqhfz
[2024-02-11 14:26:20] INFO (nni.experiment) Starting web server...
[2024-02-11 14:26:21] WARNING (nni.experiment) Timeout, retry...
[2024-02-11 14:26:22] WARNING (nni.experiment) Timeout, retry...
[2024-02-11 14:26:23] ERROR (nni.experiment) Create experiment failed: HTTPConnectionPool(host='localhost', port=8046): Max retries exceeded with url: /api/v1/nni/check-status (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fae8c0c4cd0>: Failed to establish a new connection: [Errno 111] Connection refused'))
[2024-02-11 14:26:23] INFO (nni.experiment) Creating experiment, Experiment ID: pi7wqhfz
[2024-02-11 14:26:23] INFO (nni.experiment) Starting web server...
[2024-02-11 14:26:24] WARNING (nni.experiment) Timeout, retry...
[2024-02-11 14:26:25] WARNING (nni.experiment) Timeout, retry...
[2024-02-11 14:26:26] ERROR (nni.experiment) Create experiment failed: HTTPConnectionPool(host='localhost', port=8047): Max retries exceeded with url: /api/v1/nni/check-status (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fae8c0c4490>: Failed to establish a new connection: [Errno 111] Connection refused'))
[2024-02-11 14:26:26] INFO (nni.experiment) Creating experiment, Experiment ID: pi7wqhfz
[2024-02-11 14:26:26] INFO (nni.experiment) Starting web server...
[2024-02-11 14:26:27] WARNING (nni.experiment) Timeout, retry...
[2024-02-11 14:26:28] WARNING (nni.experiment) Timeout, retry...
[2024-02-11 14:26:29] ERROR (nni.experiment) Create experiment failed: HTTPConnectionPool(host='localhost', port=8048): Max retries exceeded with url: /api/v1/nni/check-status (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fae8c1341f0>: Failed to establish a new connection: [Errno 111] Connection refused'))
[2024-02-11 14:26:29] INFO (nni.experiment) Creating experiment, Experiment ID: pi7wqhfz
[2024-02-11 14:26:29] INFO (nni.experiment) Starting web server...
[2024-02-11 14:26:30] WARNING (nni.experiment) Timeout, retry...
[2024-02-11 14:26:31] WARNING (nni.experiment) Timeout, retry...
[2024-02-11 14:26:32] ERROR (nni.experiment) Create experiment failed: HTTPConnectionPool(host='localhost', port=8049): Max retries exceeded with url: /api/v1/nni/check-status (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fae8c1341c0>: Failed to establish a new connection: [Errno 111] Connection refused'))
[2024-02-11 14:26:32] INFO (nni.experiment) Creating experiment, Experiment ID: pi7wqhfz
[2024-02-11 14:26:32] INFO (nni.experiment) Starting web server...
[2024-02-11 14:26:33] WARNING (nni.experiment) Timeout, retry...
[2024-02-11 14:26:34] WARNING (nni.experiment) Timeout, retry...
[2024-02-11 14:26:35] ERROR (nni.experiment) Create experiment failed: HTTPConnectionPool(host='localhost', port=8050): Max retries exceeded with url: /api/v1/nni/check-status (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fae8c0c67c0>: Failed to establish a new connection: [Errno 111] Connection refused'))
[2024-02-11 14:26:35] INFO (nni.experiment) Creating experiment, Experiment ID: pi7wqhfz
[2024-02-11 14:26:35] INFO (nni.experiment) Starting web server...
[2024-02-11 14:26:36] WARNING (nni.experiment) Timeout, retry...
[2024-02-11 14:26:37] WARNING (nni.experiment) Timeout, retry...
[2024-02-11 14:26:38] ERROR (nni.experiment) Create experiment failed: HTTPConnectionPool(host='localhost', port=8051): Max retries exceeded with url: /api/v1/nni/check-status (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fae8c0c5400>: Failed to establish a new connection: [Errno 111] Connection refused'))
[2024-02-11 14:26:38] INFO (nni.experiment) Creating experiment, Experiment ID: pi7wqhfz
[2024-02-11 14:26:38] INFO (nni.experiment) Starting web server...
[2024-02-11 14:26:39] WARNING (nni.experiment) Timeout, retry...
[2024-02-11 14:26:40] WARNING (nni.experiment) Timeout, retry...
[2024-02-11 14:26:41] ERROR (nni.experiment) Create experiment failed: HTTPConnectionPool(host='localhost', port=8052): Max retries exceeded with url: /api/v1/nni/check-status (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fae8c0c5b80>: Failed to establish a new connection: [Errno 111] Connection refused'))
[2024-02-11 14:26:41] INFO (nni.experiment) Creating experiment, Experiment ID: pi7wqhfz
[2024-02-11 14:26:41] INFO (nni.experiment) Starting web server...
[2024-02-11 14:26:42] WARNING (nni.experiment) Timeout, retry...
[2024-02-11 14:26:43] WARNING (nni.experiment) Timeout, retry...
[2024-02-11 14:26:44] ERROR (nni.experiment) Create experiment failed: HTTPConnectionPool(host='localhost', port=8053): Max retries exceeded with url: /api/v1/nni/check-status (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fae8c0c9220>: Failed to establish a new connection: [Errno 111] Connection refused'))
[2024-02-11 14:26:44] INFO (nni.experiment) Creating experiment, Experiment ID: pi7wqhfz
[2024-02-11 14:26:44] INFO (nni.experiment) Starting web server...
[2024-02-11 14:26:45] WARNING (nni.experiment) Timeout, retry...
[2024-02-11 14:26:46] WARNING (nni.experiment) Timeout, retry...
[2024-02-11 14:26:47] ERROR (nni.experiment) Create experiment failed: HTTPConnectionPool(host='localhost', port=8054): Max retries exceeded with url: /api/v1/nni/check-status (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fae8c0c9fa0>: Failed to establish a new connection: [Errno 111] Connection refused'))
[2024-02-11 14:26:47] INFO (nni.experiment) Creating experiment, Experiment ID: pi7wqhfz
[2024-02-11 14:26:47] INFO (nni.experiment) Starting web server...
[2024-02-11 14:26:48] WARNING (nni.experiment) Timeout, retry...
[2024-02-11 14:26:49] WARNING (nni.experiment) Timeout, retry...
[2024-02-11 14:26:50] ERROR (nni.experiment) Create experiment failed: HTTPConnectionPool(host='localhost', port=8055): Max retries exceeded with url: /api/v1/nni/check-status (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fae8c0cabb0>: Failed to establish a new connection: [Errno 111] Connection refused'))
[2024-02-11 14:26:50] INFO (nni.experiment) Creating experiment, Experiment ID: pi7wqhfz
[2024-02-11 14:26:50] INFO (nni.experiment) Starting web server...
[2024-02-11 14:26:51] WARNING (nni.experiment) Timeout, retry...
[2024-02-11 14:26:52] WARNING (nni.experiment) Timeout, retry...
[2024-02-11 14:26:53] ERROR (nni.experiment) Create experiment failed: HTTPConnectionPool(host='localhost', port=8056): Max retries exceeded with url: /api/v1/nni/check-status (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fae8c0cf0d0>: Failed to establish a new connection: [Errno 111] Connection refused'))
[2024-02-11 14:26:53] INFO (nni.experiment) Creating experiment, Experiment ID: pi7wqhfz
[2024-02-11 14:26:53] INFO (nni.experiment) Starting web server...
[2024-02-11 14:26:54] WARNING (nni.experiment) Timeout, retry...
[2024-02-11 14:26:55] WARNING (nni.experiment) Timeout, retry...
[2024-02-11 14:26:56] ERROR (nni.experiment) Create experiment failed: HTTPConnectionPool(host='localhost', port=8057): Max retries exceeded with url: /api/v1/nni/check-status (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fae8c0d21c0>: Failed to establish a new connection: [Errno 111] Connection refused'))
[2024-02-11 14:26:56] INFO (nni.experiment) Creating experiment, Experiment ID: pi7wqhfz
[2024-02-11 14:26:56] INFO (nni.experiment) Starting web server...
[2024-02-11 14:26:57] WARNING (nni.experiment) Timeout, retry...
[2024-02-11 14:26:58] WARNING (nni.experiment) Timeout, retry...
[2024-02-11 14:26:59] ERROR (nni.experiment) Create experiment failed: HTTPConnectionPool(host='localhost', port=8058): Max retries exceeded with url: /api/v1/nni/check-status (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fae8c0c9190>: Failed to establish a new connection: [Errno 111] Connection refused'))
[2024-02-11 14:27:00] INFO (nni.experiment) Creating experiment, Experiment ID: pi7wqhfz
[2024-02-11 14:27:00] INFO (nni.experiment) Starting web server...
[2024-02-11 14:27:01] WARNING (nni.experiment) Timeout, retry...
[2024-02-11 14:27:02] WARNING (nni.experiment) Timeout, retry...
[2024-02-11 14:27:03] ERROR (nni.experiment) Create experiment failed: HTTPConnectionPool(host='localhost', port=8059): Max retries exceeded with url: /api/v1/nni/check-status (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fae8c0c9910>: Failed to establish a new connection: [Errno 111] Connection refused'))
[2024-02-11 14:27:03] INFO (nni.experiment) Creating experiment, Experiment ID: pi7wqhfz
[2024-02-11 14:27:03] INFO (nni.experiment) Starting web server...
[2024-02-11 14:27:04] WARNING (nni.experiment) Timeout, retry...
[2024-02-11 14:27:05] WARNING (nni.experiment) Timeout, retry...
[2024-02-11 14:27:06] ERROR (nni.experiment) Create experiment failed: HTTPConnectionPool(host='localhost', port=8060): Max retries exceeded with url: /api/v1/nni/check-status (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fae8c0c4fd0>: Failed to establish a new connection: [Errno 111] Connection refused'))
[2024-02-11 14:27:06] INFO (nni.experiment) Creating experiment, Experiment ID: pi7wqhfz
[2024-02-11 14:27:06] INFO (nni.experiment) Starting web server...
[2024-02-11 14:27:07] WARNING (nni.experiment) Timeout, retry...
[2024-02-11 14:27:08] WARNING (nni.experiment) Timeout, retry...
[2024-02-11 14:27:09] ERROR (nni.experiment) Create experiment failed: HTTPConnectionPool(host='localhost', port=8061): Max retries exceeded with url: /api/v1/nni/check-status (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fae8c0ca160>: Failed to establish a new connection: [Errno 111] Connection refused'))
[2024-02-11 14:27:09] INFO (nni.experiment) Creating experiment, Experiment ID: pi7wqhfz
[2024-02-11 14:27:09] INFO (nni.experiment) Starting web server...
[2024-02-11 14:27:10] WARNING (nni.experiment) Timeout, retry...
[2024-02-11 14:27:11] WARNING (nni.experiment) Timeout, retry...
[2024-02-11 14:27:12] ERROR (nni.experiment) Create experiment failed: HTTPConnectionPool(host='localhost', port=8062): Max retries exceeded with url: /api/v1/nni/check-status (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fae8c0c9100>: Failed to establish a new connection: [Errno 111] Connection refused'))
[2024-02-11 14:27:12] INFO (nni.experiment) Creating experiment, Experiment ID: pi7wqhfz
[2024-02-11 14:27:12] INFO (nni.experiment) Starting web server...
[2024-02-11 14:27:13] WARNING (nni.experiment) Timeout, retry...
[2024-02-11 14:27:14] WARNING (nni.experiment) Timeout, retry...
[2024-02-11 14:27:15] ERROR (nni.experiment) Create experiment failed: HTTPConnectionPool(host='localhost', port=8063): Max retries exceeded with url: /api/v1/nni/check-status (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fae8c0c6730>: Failed to establish a new connection: [Errno 111] Connection refused'))
[2024-02-11 14:27:15] INFO (nni.experiment) Creating experiment, Experiment ID: pi7wqhfz
[2024-02-11 14:27:15] INFO (nni.experiment) Starting web server...
[2024-02-11 14:27:16] WARNING (nni.experiment) Timeout, retry...
[2024-02-11 14:27:17] WARNING (nni.experiment) Timeout, retry...
[2024-02-11 14:27:18] ERROR (nni.experiment) Create experiment failed: HTTPConnectionPool(host='localhost', port=8064): Max retries exceeded with url: /api/v1/nni/check-status (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fae8c134430>: Failed to establish a new connection: [Errno 111] Connection refused'))
[2024-02-11 14:27:18] INFO (nni.experiment) Creating experiment, Experiment ID: pi7wqhfz
[2024-02-11 14:27:18] INFO (nni.experiment) Starting web server...
[2024-02-11 14:27:19] WARNING (nni.experiment) Timeout, retry...
[2024-02-11 14:27:20] WARNING (nni.experiment) Timeout, retry...
[2024-02-11 14:27:21] ERROR (nni.experiment) Create experiment failed: HTTPConnectionPool(host='localhost', port=8065): Max retries exceeded with url: /api/v1/nni/check-status (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fae8c0cf370>: Failed to establish a new connection: [Errno 111] Connection refused'))
[2024-02-11 14:27:21] INFO (nni.experiment) Creating experiment, Experiment ID: pi7wqhfz
[2024-02-11 14:27:21] INFO (nni.experiment) Starting web server...
[2024-02-11 14:27:22] WARNING (nni.experiment) Timeout, retry...
[2024-02-11 14:27:23] WARNING (nni.experiment) Timeout, retry...
[2024-02-11 14:27:24] ERROR (nni.experiment) Create experiment failed: HTTPConnectionPool(host='localhost', port=8066): Max retries exceeded with url: /api/v1/nni/check-status (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fae8c0c4af0>: Failed to establish a new connection: [Errno 111] Connection refused'))
[2024-02-11 14:27:24] INFO (nni.experiment) Creating experiment, Experiment ID: pi7wqhfz
[2024-02-11 14:27:24] INFO (nni.experiment) Starting web server...
[2024-02-11 14:27:25] WARNING (nni.experiment) Timeout, retry...
[2024-02-11 14:27:26] WARNING (nni.experiment) Timeout, retry...
[2024-02-11 14:27:27] ERROR (nni.experiment) Create experiment failed: HTTPConnectionPool(host='localhost', port=8067): Max retries exceeded with url: /api/v1/nni/check-status (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fae8c0c6fa0>: Failed to establish a new connection: [Errno 111] Connection refused'))
[2024-02-11 14:27:27] INFO (nni.experiment) Creating experiment, Experiment ID: pi7wqhfz
[2024-02-11 14:27:27] INFO (nni.experiment) Starting web server...
[2024-02-11 14:27:28] WARNING (nni.experiment) Timeout, retry...
[2024-02-11 14:27:29] WARNING (nni.experiment) Timeout, retry...
[2024-02-11 14:27:30] ERROR (nni.experiment) Create experiment failed: HTTPConnectionPool(host='localhost', port=8068): Max retries exceeded with url: /api/v1/nni/check-status (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fae8c0d22e0>: Failed to establish a new connection: [Errno 111] Connection refused'))
[2024-02-11 14:27:30] INFO (nni.experiment) Creating experiment, Experiment ID: pi7wqhfz
[2024-02-11 14:27:31] INFO (nni.experiment) Starting web server...
[2024-02-11 14:27:32] WARNING (nni.experiment) Timeout, retry...
[2024-02-11 14:27:33] WARNING (nni.experiment) Timeout, retry...
[2024-02-11 14:27:34] ERROR (nni.experiment) Create experiment failed: HTTPConnectionPool(host='localhost', port=8069): Max retries exceeded with url: /api/v1/nni/check-status (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fae8c1349a0>: Failed to establish a new connection: [Errno 111] Connection refused'))
[2024-02-11 14:27:34] INFO (nni.experiment) Creating experiment, Experiment ID: pi7wqhfz
[2024-02-11 14:27:34] INFO (nni.experiment) Starting web server...
[2024-02-11 14:27:35] WARNING (nni.experiment) Timeout, retry...
[2024-02-11 14:27:36] WARNING (nni.experiment) Timeout, retry...
[2024-02-11 14:27:37] ERROR (nni.experiment) Create experiment failed: HTTPConnectionPool(host='localhost', port=8070): Max retries exceeded with url: /api/v1/nni/check-status (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fae8c0ca820>: Failed to establish a new connection: [Errno 111] Connection refused'))
[2024-02-11 14:27:37] INFO (nni.experiment) Creating experiment, Experiment ID: pi7wqhfz
[2024-02-11 14:27:37] INFO (nni.experiment) Starting web server...
[2024-02-11 14:27:38] WARNING (nni.experiment) Timeout, retry...
[2024-02-11 14:27:39] WARNING (nni.experiment) Timeout, retry...
[2024-02-11 14:27:40] ERROR (nni.experiment) Create experiment failed: HTTPConnectionPool(host='localhost', port=8071): Max retries exceeded with url: /api/v1/nni/check-status (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fae8c0cae50>: Failed to establish a new connection: [Errno 111] Connection refused'))
[2024-02-11 14:27:40] INFO (nni.experiment) Creating experiment, Experiment ID: pi7wqhfz
[2024-02-11 14:27:40] INFO (nni.experiment) Starting web server...
[2024-02-11 14:27:41] WARNING (nni.experiment) Timeout, retry...
[2024-02-11 14:27:42] WARNING (nni.experiment) Timeout, retry...
[2024-02-11 14:27:43] ERROR (nni.experiment) Create experiment failed: HTTPConnectionPool(host='localhost', port=8072): Max retries exceeded with url: /api/v1/nni/check-status (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fae8c0c9b50>: Failed to establish a new connection: [Errno 111] Connection refused'))
[2024-02-11 14:27:43] INFO (nni.experiment) Creating experiment, Experiment ID: pi7wqhfz
[2024-02-11 14:27:43] INFO (nni.experiment) Starting web server...
[2024-02-11 14:27:44] WARNING (nni.experiment) Timeout, retry...
[2024-02-11 14:27:45] WARNING (nni.experiment) Timeout, retry...
[2024-02-11 14:27:46] ERROR (nni.experiment) Create experiment failed: HTTPConnectionPool(host='localhost', port=8073): Max retries exceeded with url: /api/v1/nni/check-status (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fae8c134ca0>: Failed to establish a new connection: [Errno 111] Connection refused'))
[2024-02-11 14:27:46] INFO (nni.experiment) Creating experiment, Experiment ID: pi7wqhfz
[2024-02-11 14:27:46] INFO (nni.experiment) Starting web server...
[2024-02-11 14:27:47] WARNING (nni.experiment) Timeout, retry...
[2024-02-11 14:27:48] WARNING (nni.experiment) Timeout, retry...
[2024-02-11 14:27:49] ERROR (nni.experiment) Create experiment failed: HTTPConnectionPool(host='localhost', port=8074): Max retries exceeded with url: /api/v1/nni/check-status (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fae8c134bb0>: Failed to establish a new connection: [Errno 111] Connection refused'))
[2024-02-11 14:27:49] INFO (nni.experiment) Creating experiment, Experiment ID: pi7wqhfz
[2024-02-11 14:27:49] INFO (nni.experiment) Starting web server...
[2024-02-11 14:27:50] WARNING (nni.experiment) Timeout, retry...
[2024-02-11 14:27:51] WARNING (nni.experiment) Timeout, retry...
[2024-02-11 14:27:52] ERROR (nni.experiment) Create experiment failed: HTTPConnectionPool(host='localhost', port=8075): Max retries exceeded with url: /api/v1/nni/check-status (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fae8c0c6be0>: Failed to establish a new connection: [Errno 111] Connection refused'))
[2024-02-11 14:27:52] INFO (nni.experiment) Creating experiment, Experiment ID: pi7wqhfz
[2024-02-11 14:27:52] INFO (nni.experiment) Starting web server...
[2024-02-11 14:27:53] WARNING (nni.experiment) Timeout, retry...
[2024-02-11 14:27:54] WARNING (nni.experiment) Timeout, retry...
[2024-02-11 14:27:55] ERROR (nni.experiment) Create experiment failed: HTTPConnectionPool(host='localhost', port=8076): Max retries exceeded with url: /api/v1/nni/check-status (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fae8c0ca430>: Failed to establish a new connection: [Errno 111] Connection refused'))
[2024-02-11 14:27:55] INFO (nni.experiment) Creating experiment, Experiment ID: pi7wqhfz
[2024-02-11 14:27:55] INFO (nni.experiment) Starting web server...
[2024-02-11 14:27:56] WARNING (nni.experiment) Timeout, retry...
[2024-02-11 14:27:57] WARNING (nni.experiment) Timeout, retry...
[2024-02-11 14:27:58] ERROR (nni.experiment) Create experiment failed: HTTPConnectionPool(host='localhost', port=8077): Max retries exceeded with url: /api/v1/nni/check-status (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fae8c0c6ee0>: Failed to establish a new connection: [Errno 111] Connection refused'))
[2024-02-11 14:27:58] INFO (nni.experiment) Creating experiment, Experiment ID: pi7wqhfz
[2024-02-11 14:27:58] INFO (nni.experiment) Starting web server...
[2024-02-11 14:27:59] WARNING (nni.experiment) Timeout, retry...
[2024-02-11 14:28:00] WARNING (nni.experiment) Timeout, retry...
[2024-02-11 14:28:01] ERROR (nni.experiment) Create experiment failed: HTTPConnectionPool(host='localhost', port=8078): Max retries exceeded with url: /api/v1/nni/check-status (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fae8c134b50>: Failed to establish a new connection: [Errno 111] Connection refused'))
[2024-02-11 14:28:01] INFO (nni.experiment) Creating experiment, Experiment ID: pi7wqhfz
[2024-02-11 14:28:01] INFO (nni.experiment) Starting web server...
[2024-02-11 14:28:02] WARNING (nni.experiment) Timeout, retry...
[2024-02-11 14:28:03] WARNING (nni.experiment) Timeout, retry...
[2024-02-11 14:28:04] ERROR (nni.experiment) Create experiment failed: HTTPConnectionPool(host='localhost', port=8079): Max retries exceeded with url: /api/v1/nni/check-status (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fae8c0c9d00>: Failed to establish a new connection: [Errno 111] Connection refused'))
[2024-02-11 14:28:04] INFO (nni.experiment) Creating experiment, Experiment ID: pi7wqhfz
[2024-02-11 14:28:04] INFO (nni.experiment) Starting web server...
[2024-02-11 14:28:05] WARNING (nni.experiment) Timeout, retry...
[2024-02-11 14:28:06] WARNING (nni.experiment) Timeout, retry...
[2024-02-11 14:28:07] ERROR (nni.experiment) Create experiment failed: HTTPConnectionPool(host='localhost', port=8080): Max retries exceeded with url: /api/v1/nni/check-status (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fae8c0cf550>: Failed to establish a new connection: [Errno 111] Connection refused'))
[2024-02-11 14:28:08] INFO (nni.experiment) Creating experiment, Experiment ID: pi7wqhfz
[2024-02-11 14:28:08] INFO (nni.experiment) Starting web server...
[2024-02-11 14:28:09] WARNING (nni.experiment) Timeout, retry...
[2024-02-11 14:28:10] WARNING (nni.experiment) Timeout, retry...
[2024-02-11 14:28:11] ERROR (nni.experiment) Create experiment failed: HTTPConnectionPool(host='localhost', port=8081): Max retries exceeded with url: /api/v1/nni/check-status (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fae8c0d21f0>: Failed to establish a new connection: [Errno 111] Connection refused'))
[2024-02-11 14:28:11] INFO (nni.experiment) Creating experiment, Experiment ID: pi7wqhfz
[2024-02-11 14:28:11] INFO (nni.experiment) Starting web server...
[2024-02-11 14:28:12] WARNING (nni.experiment) Timeout, retry...
[2024-02-11 14:28:13] WARNING (nni.experiment) Timeout, retry...
[2024-02-11 14:28:14] ERROR (nni.experiment) Create experiment failed: HTTPConnectionPool(host='localhost', port=8082): Max retries exceeded with url: /api/v1/nni/check-status (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fae8c0c6dc0>: Failed to establish a new connection: [Errno 111] Connection refused'))
[2024-02-11 14:28:14] INFO (nni.experiment) Creating experiment, Experiment ID: pi7wqhfz
[2024-02-11 14:28:14] INFO (nni.experiment) Starting web server...
[2024-02-11 14:28:15] WARNING (nni.experiment) Timeout, retry...
[2024-02-11 14:28:16] WARNING (nni.experiment) Timeout, retry...
[2024-02-11 14:28:17] ERROR (nni.experiment) Create experiment failed: HTTPConnectionPool(host='localhost', port=8083): Max retries exceeded with url: /api/v1/nni/check-status (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fae8c1348b0>: Failed to establish a new connection: [Errno 111] Connection refused'))
[2024-02-11 14:28:17] INFO (nni.experiment) Creating experiment, Experiment ID: pi7wqhfz
[2024-02-11 14:28:17] INFO (nni.experiment) Starting web server...
[2024-02-11 14:28:18] WARNING (nni.experiment) Timeout, retry...
[2024-02-11 14:28:19] WARNING (nni.experiment) Timeout, retry...
[2024-02-11 14:28:20] ERROR (nni.experiment) Create experiment failed: HTTPConnectionPool(host='localhost', port=8084): Max retries exceeded with url: /api/v1/nni/check-status (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fae8c0d2610>: Failed to establish a new connection: [Errno 111] Connection refused'))
[2024-02-11 14:28:20] INFO (nni.experiment) Creating experiment, Experiment ID: pi7wqhfz
[2024-02-11 14:28:20] INFO (nni.experiment) Starting web server...
[2024-02-11 14:28:21] WARNING (nni.experiment) Timeout, retry...
[2024-02-11 14:28:22] WARNING (nni.experiment) Timeout, retry...
[2024-02-11 14:28:23] ERROR (nni.experiment) Create experiment failed: HTTPConnectionPool(host='localhost', port=8085): Max retries exceeded with url: /api/v1/nni/check-status (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fae8c0ca280>: Failed to establish a new connection: [Errno 111] Connection refused'))
[2024-02-11 14:28:23] INFO (nni.experiment) Creating experiment, Experiment ID: pi7wqhfz
[2024-02-11 14:28:23] INFO (nni.experiment) Starting web server...
[2024-02-11 14:28:24] WARNING (nni.experiment) Timeout, retry...
[2024-02-11 14:28:25] WARNING (nni.experiment) Timeout, retry...
[2024-02-11 14:28:26] ERROR (nni.experiment) Create experiment failed: HTTPConnectionPool(host='localhost', port=8086): Max retries exceeded with url: /api/v1/nni/check-status (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fae8c134b80>: Failed to establish a new connection: [Errno 111] Connection refused'))
[2024-02-11 14:28:26] INFO (nni.experiment) Creating experiment, Experiment ID: pi7wqhfz
[2024-02-11 14:28:26] INFO (nni.experiment) Starting web server...
[2024-02-11 14:28:27] WARNING (nni.experiment) Timeout, retry...
[2024-02-11 14:28:28] WARNING (nni.experiment) Timeout, retry...
[2024-02-11 14:28:29] ERROR (nni.experiment) Create experiment failed: HTTPConnectionPool(host='localhost', port=8087): Max retries exceeded with url: /api/v1/nni/check-status (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fae8c0c5820>: Failed to establish a new connection: [Errno 111] Connection refused'))
[2024-02-11 14:28:29] INFO (nni.experiment) Creating experiment, Experiment ID: pi7wqhfz
[2024-02-11 14:28:29] INFO (nni.experiment) Starting web server...
[2024-02-11 14:28:30] WARNING (nni.experiment) Timeout, retry...
[2024-02-11 14:28:31] WARNING (nni.experiment) Timeout, retry...
[2024-02-11 14:28:32] ERROR (nni.experiment) Create experiment failed: HTTPConnectionPool(host='localhost', port=8088): Max retries exceeded with url: /api/v1/nni/check-status (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fae8c0d2640>: Failed to establish a new connection: [Errno 111] Connection refused'))
[2024-02-11 14:28:32] INFO (nni.experiment) Creating experiment, Experiment ID: pi7wqhfz
[2024-02-11 14:28:32] INFO (nni.experiment) Starting web server...
[2024-02-11 14:28:33] WARNING (nni.experiment) Timeout, retry...
[2024-02-11 14:28:34] WARNING (nni.experiment) Timeout, retry...
[2024-02-11 14:28:35] ERROR (nni.experiment) Create experiment failed: HTTPConnectionPool(host='localhost', port=8089): Max retries exceeded with url: /api/v1/nni/check-status (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fae8c0d2340>: Failed to establish a new connection: [Errno 111] Connection refused'))
[2024-02-11 14:28:35] INFO (nni.experiment) Stopping experiment, please wait...
[2024-02-11 14:28:35] INFO (nni.experiment) Saving experiment checkpoint...
[2024-02-11 14:28:35] INFO (nni.experiment) Stopping NNI manager, if any...
